### ISSUE TITLE
Specify version for CI tests

### ISSUE THREAD

**Issue by EdgarBarrantes** [aave-starknet-project/aave-starknet-core#110]
If [this PR](https://github.com/software-mansion/protostar/pull/649) is accepted, we should change our [tests.yml](https://github.com/aave-starknet-project/aave-starknet-core/blob/main/.github/workflows/tests.yml#L21) to specify a protostar version to use by changing that line to:

```shell
curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash  -s -- -v 0.3.2
```

**Comment by achab** [comment]
protostar contributor here :eyes:
