### ISSUE TITLE
[Research] Empty structs

### ISSUE THREAD

**Issue by kaliberpoziomka** [aave-starknet-project/aave-starknet-core#126]
In Cairo empty structs (i.e. structs that didn't receive any value) behave like enums. A simple example of such behavior would be the `Uint256` struct initialized with no values. In such case `Uint256.low` would be `1` and `Uint256.high` would be `2`. Should we create some helper function to check if we access the struct's data and not just numbers that represent enum fields? Is this even possible to pass an empty struct to the function? Or is this potential error actually not possible in real cases?

**Comment by achab** [comment]
Not sure to get this one. Only struct instances (`let my_int = Uint256(low=5, high=0)`) have data and struct "classes" (`Uint256.low`) behave like enums. Not sure we can pass a struct "class" to a function, it would not compile IMO.

In our codebase, we use this enum behavior several times (error messages and last argument of `update_struct` helper function).
