### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-core#28]
- [x] Rename values.cairo to constants.cairo
- [ ] Rename "helpers" file/folder which is too generic
- [ ] Format imports (add PEP8 in pre-commit?)
- [x] Review use of namespaces (for constant file for instance)
- [x] Remove useless statements `%lang starknet`
- [x] Use [Data Transformers](https://docs.swmansion.com/protostar/docs/tutorials/guides/testing#data-transformer) to refactor tests 
- [x] Use only one statement that could fail in a `with_attr error_message(...)` block

**Comment by msaug** [comment]
We can also refactor the test deployments with [Data Transformers](https://docs.swmansion.com/protostar/docs/tutorials/guides/testing#example) to improve readability

**Comment by msaug** [comment]
I also think we should make sure that when we use `with_attr error_message("..."):`, the only possible source of error in that block is the expected one. For example, we should only keep assertions and remove remote contract calls that might also generate an error, because the tests would not be able to detect unexpected errors. I had this problem with some tests yesterday and couldn't understand why they passed when they were supposed to fail.

**Comment by achab** [comment]
You mean that you called a function in a `with_attr` statement, and it has hidden (or overridden) the error message from the function?

**Comment by msaug** [comment]
I had this code block :
``` 
with_attr error_message("AToken supply is not zero"):
            let (a_token_supply) = IERC20.totalSupply(contract_address=reserve.a_token_address)
            assert a_token_supply = Uint256(0, 0)
end
```
    Which is supposed to throw an error when `a_token_supply` is not 0 - It actually threw an error because IERC20.totalSupply is not a valid entrypoint because the AToken contract doesn't implement it yet. So I was expecting a revert because a_token_supply was > 0, but actually got a revert because of another reason.

**Comment by achab** [comment]
ok got it! so we should only put asserts in `with_attr error_message("...")` blocks, right? adding this to the list

**Comment by msaug** [comment]
Yes, or at least make sure that there's only one expression that can potentially fail

**Comment by achab** [comment]
1. helpers / utils / misc are catch-all filenames, and it's always better to be specific when we can. so far (with helpers/helpers.cairo on main) here I don't have a better option. this point is a reminder rather than a "call to action"
2. indeed PEP8 is only for python, and tweaking a pre-commit would be overkill. I just wanted to highlight the guidelines 7 from this file: https://www.notion.so/nethermind/Cairo-coding-guidelines-c91adce7277544e6ab191a9d67cc860a

**Comment by achab** [comment]
Hey @msaug, what was the reason to re-open this issue? I think it's a mistake since the two remaining points won't be addressed.

**Comment by msaug** [comment]
My bad, if we don't address the remaining points it can be closed.
