### ISSUE TITLE
Debt tokens: implement StableDebtToken and VariableDebtToken contracts

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-core#46]
We should implement StableDebtToken and VariableDebtToken contracts, solidity contracts being here: https://github.com/aave/aave-v3-core/tree/master/contracts/protocol/tokenization. Those contracts are deployed while initiating a new asset's reserve.

**Comment by msaug** [comment]
Divided into https://github.com/aave-starknet-project/aave-starknet-core/issues/52, https://github.com/aave-starknet-project/aave-starknet-core/issues/53, https://github.com/aave-starknet-project/aave-starknet-core/issues/54
