### ISSUE TITLE
Debt tokens: implement VariableDebtToken 

### ISSUE THREAD

**Issue by msaug** [aave-starknet-project/aave-starknet-core#53]
We should implement the VariableDebtToken solidity contract being here: https://github.com/aave/aave-v3-core/tree/master/contracts/protocol/tokenization. This contract is deployed while initiating a new asset's reserve.

We can start working on this once https://github.com/aave-starknet-project/aave-starknet-core/issues/54 and https://github.com/aave-starknet-project/aave-starknet-core/issues/29 are closed

More details on [Notion](https://www.notion.so/nethermind/VariableDebtToken-0bfee0a2dc7c40219a854eb8143cd528)

**Comment by EdgarBarrantes** [comment]
Shall we perhaps close #46 and divide it into two issues?
