### ISSUE TITLE
Implement WadRayMath tests

### ISSUE THREAD

**Issue by EdgarBarrantes** [aave-starknet-project/aave-starknet-core#82]

**Comment by achab** [comment]
@EdgarBarrantes we wrote some tests in js for Phase 1: https://github.com/aave-starknet-project/aave-starknet-bridge/blob/main/test/wad_ray_math.test.ts

**Comment by EdgarBarrantes** [comment]
Great! Thanks, do you think we should close this issue or leave it and implement those in Cairo with protostar eventually?

**Comment by achab** [comment]
Ideally, we also test it in cairo in our repo. We can leave the issue here for now, it can a good "first issue" for potential newcomers.
