### ISSUE TITLE
update contracts to use consistent error messages

### ISSUE THREAD

**Issue by hsouf** [aave-starknet-project/aave-starknet-core#95]

**Comment by achab** [comment]
Thanks for raising this! IMO, the different choices are:
1. use explicit sentences
2. use short sentences or group of words "reserve paused", etc.
3. use an enum (like create a struct Errors, with members Erros.RESERVE_PAUSED). this would mimick aave-v3-core behavior

**Comment by msaug** [comment]
I think we should go with the enum. Users will be able to report to the [Troubleshooting Errors table](https://docs.aave.com/developers/v/2.0/guides/troubleshooting-errors) to know what the error is.
