### ISSUE TITLE
Refactoring: error messages

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-core#96]
The goal of this issue is to refactor error messages, and follow Errors.sol library from Aave (https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/libraries/helpers/Errors.sol).

The proposal is: we create a struct that acts as an enum, and use similar code than solidity ones. It would work because struct values are initialized with the index of the attribute. That is:

```cairo
struct Errors:
    member CALLER_NOT_RISK_OR_POOL_ADMIN : felt # corresponds to the value 1
    member CALLER_NOT_EMERGENCY_ADMIN : felt # corresponds to the value 2
    ...
end
```

Then, in `with_attr` statement, since only strings are accepted, we would write:

```cairo
with_attr error_message("{Errors.CALLER_NOT_RISK_OR_POOL_ADMIN}"):
    # assert something
end
```

**Comment by msaug** [comment]
```cairo
 with_attr error_message("{Errors.CALLER_NOT_RISK_OR_POOL_ADMIN}"):
        assert allowance = TRUE
 end
 ```
 
 throws this message :
 `— {Errors.CALLER_NOT_RISK_OR_POOL_ADMIN} (Cannot evaluate ap-based or complex references: ['Errors.CALLER_NOT_RISK_OR_POOL_ADMIN'])`
 
A potential workaround is this : 

```cairo
let error_code = Errors.CALLER_NOT_RISK_OR_POOL_ADMIN
with_attr error_message("{error_code}"):
    # assert something
end
```

which throws the expected value, i.e. `3`.

**Comment by hsouf** [comment]
declaring the error before using it just adds extra lines of code, let's say we are doing 3 checks, that would entail having 3 lines for each error type...

**Comment by hsouf** [comment]
declaring the error before using it just adds extra lines of code, let's say we are doing 3 checks, that would entail having 3 lines for each error type...

**Comment by kaliberpoziomka** [comment]
Maybe we should create error messages not as a struct but as a namespace with constants?
```
namespace Errors:
  const ERROR_CALLER_NOT_RISK_OR_POOL_ADMIN = "ERROR MESSAGE #1"
  const ERROR_CALLER_NOT_EMERGENCY_ADMIN = " ERROR MESSAGE #2"
  ...
end
```

**Comment by achab** [comment]
Nice approach @kaliberpoziomka ! We indeed probably need to use constants to avoid evaluation in `with_attr` statement. As error messages, we can keep integers used on solidity side. Also, you proposal enables a quick refactoring

**Comment by msaug** [comment]
> Maybe we should create error messages not as a struct but as a namespace with constants?
> 
> ```
> namespace Errors:
>   const CALLER_NOT_RISK_OR_POOL_ADMIN = "ERROR MESSAGE #1"
>   const CALLER_NOT_EMERGENCY_ADMIN = " ERROR MESSAGE #2"
>   ...
> end
> ```

Unfortunately this doesn't help. This error is thrown during the evalutation of the error message : 
`starkware.cairo.lang.compiler.preprocessor.flow.MissingReferenceError: Missing reference contracts.protocol.libraries.helpers.errors.Errors.RESERVE_INACTIVE.`

Unless I reference it by doing 
```cairo
        let err = Errors.RESERVE_INACTIVE
        with_attr error_message("{err}"):
            assert is_active = TRUE
        end
```
Not sure why exactly, but my guess would be that in error messages you can only use variables that have been used during runtime, i.e. that were pushed to `ap`. Therefore we can't use constants directly in our error messages.

**Comment by EdgarBarrantes** [comment]
> declaring the error before using it just adds extra lines of code, let's say we are doing 3 checks, that would result in 3 lines of code for each error type...

True, but trying different approaches in the playground (tuples, functions, and the above) bear the same result, msaug might be right regarding the `ap` pushed variables. Redeclaring the variable might actually be the way to go. Just a side note, that might even imply one more line (`err` variable should be local, if we want to keep it consistent across a file, so alloc_locals should also be added), eg:

```cairo
struct Errors:
    member CALLER_NOT_RISK_OR_POOL_ADMIN : felt # corresponds to the value 1
    member CALLER_NOT_EMERGENCY_ADMIN : felt # corresponds to the value 2
end

func main{output_ptr : felt*}():
    alloc_locals
    local err = Errors.CALLER_NOT_RISK_OR_POOL_ADMIN
    with_attr error_message("{err}"):
        assert 1 = 0
    end
    return ()
end
```

**Comment by achab** [comment]
Hmm, indeed it's not a simple as expected. I'm actually happy with @msaug's workaround to define `err_code` first and then use it in `with_attr` statement. 

@hsouf It's one more line to add, but it forces us to check the corresponding Error code and prevents us from typos. One line is not a lot compared to the extra lines of code we had because of `Uint256`. Also, when it will become possible to pass directly `Error.SOME_ERROR` in `with_attr`, it will be easier to refactor.
